# Generated by Django 3.2.5 on 2021-11-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='عکس پروفایل'),
        ),
        migrations.DeleteModel(
            name='ProfileImg',
        ),
    ]
