# Generated by Django 3.2.5 on 2021-11-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20211108_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='f.jpg', null=True, upload_to='image', verbose_name='عکس پروفایل'),
        ),
    ]
