# Generated by Django 3.2.5 on 2021-09-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rate',
            field=models.CharField(default=False, max_length=3),
        ),
    ]
