# Generated by Django 3.2.5 on 2021-09-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='age',
            field=models.CharField(default='PG-13', max_length=10),
        ),
        migrations.AddField(
            model_name='article',
            name='director',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='release',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='stars',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='time',
            field=models.CharField(default='', max_length=10),
        ),
    ]
