# Generated by Django 3.2.5 on 2021-09-30 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210930_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ctagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='لینک')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('position', models.IntegerField(verbose_name='پوزیشن')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['position'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AlterField(
            model_name='article',
            name='age',
            field=models.CharField(default='PG-13', max_length=10, verbose_name='درجه سنی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(verbose_name='کپشن'),
        ),
        migrations.AlterField(
            model_name='article',
            name='director',
            field=models.CharField(default='', max_length=20, verbose_name='کارگردان'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='article',
            name='rate',
            field=models.CharField(default=0, max_length=3, verbose_name='نمره'),
        ),
        migrations.AlterField(
            model_name='article',
            name='release',
            field=models.CharField(default='', max_length=20, verbose_name='زمان انتشار فیلم'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='article',
            name='star',
            field=models.BooleanField(default=False, verbose_name='برگزیده'),
        ),
        migrations.AlterField(
            model_name='article',
            name='stars',
            field=models.CharField(default='', max_length=100, verbose_name='ستارگان'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Publish')], max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(upload_to='images', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.CharField(default='', max_length=10, verbose_name='زمان فیلم'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
    ]
