# Generated by Django 3.2.5 on 2021-09-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210930_0438'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ctagory',
            new_name='Category',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='blog.Category', verbose_name='دسته بندی'),
        ),
    ]
