# Generated by Django 3.2.5 on 2021-10-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210930_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='daste',
            field=models.CharField(choices=[('S', 'Series'), ('F', 'Film')], default=(('S', 'Series'), ('F', 'Film')), max_length=1, verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='articles', to='blog.Category', verbose_name='دسته بندی'),
        ),
    ]
