# Generated by Django 3.2.5 on 2021-11-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_article_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAdderss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipadderss', models.GenericIPAddressField()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='blog.IpAdderss', verbose_name='بازدیدها'),
        ),
    ]
