# Generated by Django 3.2.5 on 2021-11-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20211122_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipadderss',
            name='ipadderss',
        ),
        migrations.AddField(
            model_name='ipadderss',
            name='ip_address',
            field=models.GenericIPAddressField(default=0, verbose_name='آدرس آی\u200cپی'),
            preserve_default=False,
        ),
    ]
